#!/usr/bin/env php
<?php

if (!defined("SIGINT")) define("SIGINT", 2);
if (!defined("SIGTERM")) define("SIGTERM", 15);
if (!defined("SIGTSTP")) define("SIGTSTP", 20);

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
